@moduleEndpoint = {{ host }}/auth

### Create a new user
POST {{ moduleEndpoint }}/signup
Content-Type: application/json

{
	"email": "user1@sdf.com",
	"password": "supersecretpassword"
}

### Find a particular user with a given ID
GET {{ moduleEndpoint }}/1
### Find a particular user with a given ID /BAD/
GET {{ moduleEndpoint }}/919283

### Find all users with a given email
GET {{ moduleEndpoint }}?email=user1@sdf.com

### Delete an user with a given ID number
DELETE {{ moduleEndpoint }}/3

### Update user with a given ID number and body payload
PATCH {{ moduleEndpoint }}/1
Content-Type: application/json

{
	"email": "user0@sdf.com",
	"password": "supersecretpassword2"
}